### ISSUE TITLE
QHD (3440x1440) Crashing

### ISSUE THREAD

**Issue by ProtocolHD** [Blightbuster/RatScanner#25] opened 2020-10-05 03:12 UTC
**Describe the bug**
I am opening up this bug report as the auto-bug report wasn't working for me. I intend on updating it with more precise information as I can replicate the crashes

**To Reproduce**
1. Start Running Software
2. Move around in game / go between flea market searches/vendors/etc. while outside of raid.
3. Program should crash rather quickly.

**Expected behavior**
Uhh... it shouldn't crash? 

**Additional context**
If I sit in my stash and use it, it works pretty much perfectly minus its image lookup being a little screwy. But as soon as I either bounce around menus OR if I'm in raid and I'm running around it almost always crashes within 5 minutes meaning I either have to not use it or it constantly needs to be re-launched. I will try to get error logs soon.

**Comment by ProtocolHD** [comment] 2020-10-05 03:21
[03:10:07.5975586] > [Info]  ----- RatScanner 2.2.1 -----
[03:10:07.6026202] > [Info]  Starting RatScanner...
[03:10:07.6077888] > [Info]  Loading config...
[03:10:07.6255026] > [Info]  Loading price data...
[03:10:08.1119421] > [Info]  Setting default item...
[03:10:08.1212561] > [Info]  Initializing name scan...
[03:10:08.1257082] > [Info]  Loading OCR data...
[03:10:08.2014812] > [Info]  Initializing icon scan...
[03:10:08.2061731] > [Info]  Loading static icons...
[03:10:08.2889478] > [Info]  Loaded 1141/1141 icons successfully.
[03:10:08.2940222] > [Info]  Loading dynamic icons...
[03:10:08.4705344] > [Info]  Loaded 1830/1830 icons successfully.
[03:10:08.4793814] > [Info]  Loading static correlation data...
[03:10:08.4934691] > [Info]  Loading dynamic correlation data...
[03:10:08.5340776] > [Info]  Initializing file watcher for icon cache...
[03:10:08.5397439] > [Info]  Prewarming name tool tip...
[03:10:08.7243802] > [Info]  Prewarming icon tool tip...
[03:10:08.7595724] > [Info]  Registering mouse and keyboard hooks...
[03:10:08.7665030] > [Info]  Ready!
[03:10:08.7733068] > [Info]  Loading resource "RSClientVersion"...
[03:10:09.1177228] > [Info]  Loading resource "RSPatreon"...
[03:10:09.3617467] > [Info]  Loading resource "RSDiscord"...
[03:10:09.6133343] > [Info]  Loading resource "RSGithub"...
[03:13:11.4387162] > [Info]  Saving config...
[03:14:11.0725967] > [Warning] Could not find icon key for:
Uid: 55d482194bdc2d1d4e8b456b
[03:14:11.0819599] > [Warning] Could not find icon key for:
Uid: 55d482194bdc2d1d4e8b456b
[03:14:11.0874582] >    at System.Environment.get_StackTrace()
   at RatScanner.IconManager.GetIconPath(ItemInfo itemInfo)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at MS.Internal.Data.PropertyPathWorker.GetValue(Object item, Int32 level)
   at MS.Internal.Data.PropertyPathWorker.RawValue(Int32 k)
   at MS.Internal.Data.PropertyPathWorker.RawValue()
   at MS.Internal.Data.ClrBindingWorker.RawValue()
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.RefreshValue()
   at MS.Internal.Data.ClrBindingWorker.ScheduleTransferOperation(Object arg)
   at MS.Internal.Data.DataBindOperation.Invoke()
   at MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at RatScanner.App.Main()
[03:14:11.6410437] > [Warning] Could not find icon key for:
Uid: 55d482194bdc2d1d4e8b456b
[03:14:11.6472800] >    at System.Environment.get_StackTrace()
   at RatScanner.IconManager.GetIconPath(ItemInfo itemInfo)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at MS.Internal.Data.PropertyPathWorker.GetValue(Object item, Int32 level)
   at MS.Internal.Data.PropertyPathWorker.RawValue(Int32 k)
   at MS.Internal.Data.PropertyPathWorker.RawValue()
   at MS.Internal.Data.ClrBindingWorker.RawValue()
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.RefreshValue()
   at MS.Internal.Data.ClrBindingWorker.ScheduleTransferOperation(Object arg)
   at MS.Internal.Data.DataBindOperation.Invoke()
   at MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at RatScanner.App.Main()
[03:20:50.6037003] > [Info]  Loading dynamic icons...
[03:20:50.9737123] > [Info]  Loaded 1831/1831 icons successfully.
[03:20:51.0818328] > [Info]  Loading dynamic correlation data...
[03:20:51.1221810] > [Info]  Loading dynamic icons...
[03:20:51.3618892] > [Info]  Loaded 1831/1831 icons successfully.
[03:20:51.3702058] > [Info]  Loading dynamic correlation data...
[03:21:01.8408318] > [Info]  Loading dynamic icons...
[03:21:02.1904549] > [Info]  Loaded 1832/1832 icons successfully.
[03:21:02.2019576] > [Info]  Loading dynamic correlation data...
[03:21:02.2618324] > [Info]  Loading dynamic icons...
[03:21:02.5882870] > [Info]  Loaded 1832/1832 icons successfully.
[03:21:02.5973663] > [Info]  Loading dynamic correlation data...
[03:21:19.2800837] > [Info]  Loading dynamic icons...
[03:21:19.6208111] > [Info]  Loaded 1833/1833 icons successfully.
[03:21:19.6323415] > [Info]  Loading dynamic correlation data...
[03:21:19.8043338] > [Error] Unhandled exception in RatScanner v2.2.1.0
 -------------------- 
 System.IO.IOException: The process cannot access the file 'C:\Users\17852\AppData\Local\Temp\Battlestate Games\EscapeFromTarkov\Icon Cache\index.json' because it is being used by another process.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at RatScanner.IconManager.LoadDynamicCorrelationData()
   at RatScanner.IconManager.OnDynamicCorrelationDataChange(Object source, FileSystemEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by Blightbuster** [comment] 2020-10-05 09:16
Duplicate of #19 

Fixed in next release.

**Closed by Blightbuster** 2020-10-05 09:16 UTC
Labels: bug, duplicate
