### ISSUE TITLE
Unhandled exception in RatScanner v2.2.1.0

### ISSUE THREAD

**Issue by asdf5366** [Blightbuster/RatScanner#29] opened 2020-10-05 16:00 UTC
**Error**
Unhandled exception in RatScanner v2.2.1.0
```
System.IO.IOException: The process cannot access the file 'C:\Users\asdf5\AppData\Local\Temp\Battlestate Games\EscapeFromTarkov\Icon Cache\index.json' because it is being used by another process.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at RatScanner.IconManager.LoadDynamicCorrelationData()
   at RatScanner.IconManager.OnDynamicCorrelationDataChange(Object source, FileSystemEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```
<details>
<summary>Log</summary>

```
[15:59:27.3404244] > [Info]  ----- RatScanner 2.2.1 -----
[15:59:27.3419397] > [Info]  Starting RatScanner...
[15:59:27.3424167] > [Info]  Loading config...
[15:59:27.3660920] > [Info]  Loading price data...
[15:59:28.6838815] > [Info]  Setting default item...
[15:59:28.6926525] > [Info]  Initializing name scan...
[15:59:28.6936341] > [Info]  Loading OCR data...
[15:59:28.8106062] > [Info]  Initializing icon scan...
[15:59:28.8127305] > [Info]  Loading static icons...
[15:59:29.0436222] > [Info]  Loaded 1141/1141 icons successfully.
[15:59:29.0443159] > [Info]  Loading dynamic icons...
[15:59:29.1275771] > [Info]  Loaded 379/379 icons successfully.
[15:59:29.1299365] > [Info]  Loading static correlation data...
[15:59:29.1413997] > [Info]  Loading dynamic correlation data...
[15:59:29.1559547] > [Info]  Initializing file watcher for icon cache...
[15:59:29.1584925] > [Info]  Prewarming name tool tip...
[15:59:29.5774263] > [Info]  Prewarming icon tool tip...
[15:59:29.6568127] > [Info]  Registering mouse and keyboard hooks...
[15:59:29.6584546] > [Info]  Ready!
[15:59:29.6616341] > [Info]  Loading resource "RSClientVersion"...
[15:59:30.4930332] > [Info]  Loading resource "RSPatreon"...
[15:59:31.1229582] > [Info]  Loading resource "RSDiscord"...
[15:59:31.7872197] > [Info]  Loading resource "RSGithub"...
[15:59:51.0568119] > [Info]  Loading dynamic icons...
[15:59:51.1588506] > [Info]  Loaded 380/380 icons successfully.
[15:59:51.1592879] > [Info]  Loading dynamic correlation data...
[15:59:51.1653803] > [Info]  Loading dynamic icons...
[15:59:51.2454215] > [Info]  Loaded 380/380 icons successfully.
[15:59:51.2458310] > [Info]  Loading dynamic correlation data...
[16:00:15.1370562] > [Info]  Loading dynamic icons...
[16:00:15.2326572] > [Info]  Loaded 381/381 icons successfully.
[16:00:15.2331481] > [Info]  Loading dynamic correlation data...
[16:00:15.2378786] > [Info]  Loading dynamic icons...
[16:00:15.3226530] > [Info]  Loaded 381/381 icons successfully.
[16:00:15.3231040] > [Info]  Loading dynamic correlation data...
[16:00:15.8817369] > [Info]  Loading dynamic icons...
[16:00:15.9838857] > [Info]  Loaded 382/382 icons successfully.
[16:00:15.9843621] > [Info]  Loading dynamic correlation data...
[16:00:15.9893597] > [Info]  Loading dynamic icons...
[16:00:16.0782882] > [Info]  Loaded 382/382 icons successfully.
[16:00:16.0787202] > [Info]  Loading dynamic correlation data...
[16:00:16.1063746] > [Error] Unhandled exception in RatScanner v2.2.1.0
 -------------------- 
 System.IO.IOException: The process cannot access the file 'C:\Users\asdf5\AppData\Local\Temp\Battlestate Games\EscapeFromTarkov\Icon Cache\index.json' because it is being used by another process.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at RatScanner.IconManager.LoadDynamicCorrelationData()
   at RatScanner.IconManager.OnDynamicCorrelationDataChange(Object source, FileSystemEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```
</details>

**Comment by Blightbuster** [comment] 2020-10-05 16:08
Duplicate of #19 
Fix will be merged into master when next release is ready.

**Closed by Blightbuster** 2020-10-05 16:08 UTC
Labels: bug, duplicate
