### ISSUE TITLE
Item price mismatches tarkov-market

### ISSUE THREAD

**Issue by Quipex** [Blightbuster/RatScanner#6] opened 2020-09-23 10:32 UTC
The problem is that item is detected correctly, but actual price is wrong and is different from tarkov-market

### Wrong price:
![Wrong price](https://i.imgur.com/FedC0yO.png)

### Actual price:
![Actual price](https://user-images.githubusercontent.com/30311108/94000995-93884f00-fda0-11ea-853a-eaf9f15c895d.png)

**Comment by Blightbuster** [comment] 2020-09-23 10:46
Did you scan the item with icon scan or name scan? If you did with icon scan, the price will include all mods on the gun.

Perhaps we should display the price of the base item and mods separately to make this clear to users?

**Comment by Blightbuster** [comment] 2020-09-23 11:11
However the calculated weapon price, including mods ( when using icon scan ), will be to high since the tarkov-market api currently only provides prices for functioning items. This means that the gun price from the api already includes the price of some mods, attached to it, to have it in a "functioning" state. A fix for this will require the tarkov-market api to support prices of non functioning items.

**Comment by Quipex** [comment] 2020-09-23 11:44
> Did you scan the item with icon scan or name scan? If you did with icon scan, the price will include all mods on the gun.
> 
> Perhaps we should display the price of the base item and mods separately to make this clear to users?

I've scanned by the name. Actually, the price is the same both ways.

**Comment by Quipex** [comment] 2020-09-23 11:46
> Perhaps we should display the price of the base item and mods separately to make this clear to users?
At least it should tell user that it's the price of a modded item

**Comment by Blightbuster** [comment] 2020-09-23 14:44
> At least it should tell user that it's the price of a modded item
I created #7 to track this issue.

> I've scanned by the name. Actually, the price is the same both ways.
I was able to reproduce this by icon scanning the gun first and then name scanning it. This will result in the described bug.

**Closed** 2020-09-23 15:34 UTC
Labels: bug
